#! /usr/bin/python
import sys
import logging

from context import librelaws
from librelaws import cli

parser = cli.create_parser()
args = parser.parse_args()

try:
    args.func(args)
except KeyboardInterrupt:
    sys.exit(1)
except Exception as e:
    if args.verbose:
        logging.basicConfig(level=logging.DEBUG)
        # re-raise with the full traceback
        t, v, tb = sys.exc_info()
        raise t(v).with_traceback(tb)
    else:
        sys.exit("{0}: {1}".format(e.__class__.__name__, e))
